# Change these first
owner: askofcc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MA Education
    url: https://uptime.ma.edu.kg/

status-website:
  baseUrl: /upptime
  name: MA Education Uptime
  introTitle: "**MA Education** 服务状态监控"
  introMessage: 实时查看 MA Education 各服务的运行状态与响应时间。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

